data:
  batch_size: 32
  dir: datasets/
  graph_num: 2250
  init: degrees
  max_feat_num: 6
  max_node_num: 9
  name: Letter_high
  num_workers: 4
  test_class_num: 4
  test_split: 0.2
  train_class_num: 11
debug: false
device: cuda:1
device_count: 1
encoder_path: checkpoints/Letter_high_HGCN_encoder_train/20250526_212414/best.pth
exp_name: Letter_high_score_network_proto_train_hgcn
fsl_task:
  K_shot: 5
  N_way: 4
  P_num_task: 10
  R_query: 10
run_name: Letter_high_score_network_proto_train_hgcn/20250527_205008
score_model_a:
  adim: 32
  c: 1.0
  c_final: 4
  c_hid: 8
  c_init: 2
  conv: GCN
  manifold: PoincareBall
  max_feat_num: 64
  max_node_num: 9
  model_class: ScoreNetworkA_poincare
  nhid: 32
  num_heads: 4
  num_layers: 5
  num_linears: 3
score_model_x:
  GCN_type: HGCN
  c: 1.0
  depth: 5
  edge_dim: 1
  manifold: PoincareBall
  max_feat_num: 64
  model_class: ScoreNetworkX_poincare
  nhid: 32
sde:
  adj:
    beta_max: 0.5
    beta_min: 0.05
    num_scales: 1000
    type: VE
  x:
    beta_max: 0.1
    beta_min: 0.005
    num_scales: 1000
    type: VP
seed: 42
timestamp: '20250527_205008'
train:
  beta1: 0.9
  beta2: 0.999
  ema: 0.999
  eps: 0.001
  eval_interval: 10
  grad_norm: 0.1
  kl_regularization: 1.0e-05
  lr: 0.0001
  lr_decay: 0.999
  lr_schedule: false
  min_lr: 1.0e-08
  num_epochs: 1000
  optimizer: Adam
  print_interval: 5
  proto_loss_weight: 0.001
  proto_update_freq: 1
  reduce_mean: true
  save_interval: 10
  use_proto_regularization: true
  warmup_epochs: 0
  weight_decay: 0.0001
wandb:
  entity: huangyr_team
  no_wandb: false
  online: true
  project: MHGDM
  wandb_usr: huangyr
