data:
  batch_size: 128
  dir: datasets/
  graph_num: 2250
  init: degrees
  max_feat_num: 6
  max_node_num: 9
  name: Letter_high
  test_class_num: 4
  test_split: 0.2
  train_class_num: 11
debug: false
device: cuda
exp_name: Letter_high_score_debug_test
fsl_task:
  k_shot: 5
  n_way: 5
  query_num: 15
model:
  GCN_type: HGAT
  act: LeakyReLU
  adim: 32
  adj:
    model_class: ScoreNetworkA_poincare
  aggregation_method: sum
  c: 0.01
  c_final: 4
  c_hid: 8
  c_init: 2
  conv: GCN
  dec_layers: 3
  depth: 5
  dim: 10
  dropout: 0.0
  edge_dim: 1
  enc_layers: 3
  encoder_path: checkpoints/Letter_high_HGCN_encoder_train/20250526_212414/best.pth
  hidden_dim: 32
  manifold: PoincareBall
  msg_transform: true
  nhid: 32
  normalization_factor: 1
  num_heads: 4
  num_layers: 7
  num_linears: 2
  sum_transform: true
  use_centroid: false
  use_norm: ln
  x:
    model_class: ScoreNetworkX_poincare
run_name: Letter_high_score_debug_test/20250527_171356
sde:
  adj:
    beta_max: 1.0
    beta_min: 0.2
    num_scales: 1000
    type: VE
  x:
    beta_max: 1.0
    beta_min: 0.1
    num_scales: 1000
    type: VP
seed: 1
timestamp: '20250527_171356'
train:
  ema: 0.999
  eps: 1.0e-05
  grad_norm: 1.0
  kl_regularization: 1.0e-05
  lr: 0.01
  lr_decay: 0.999
  lr_schedule: true
  num_epochs: 5000
  print_interval: 100
  reduce_mean: true
  save_interval: 500
  weight_decay: 0.0001
wandb:
  entity: huangyr_team
  no_wandb: false
  online: true
  project: MHGDM
  wandb_usr: huangyr
