model_type: adj_poincare_proto
max_feat_num: ${model.max_feat_num}  # 引用基础配置中的值
max_node_num: ${model.max_node_num}  # 引用基础配置中的值
nhid: 32
num_layers: 7
num_linears: 2
c_init: 2
c_hid: 8
c_final: 4
adim: 32
num_heads: 4
conv: GCN
manifold: Lorentz
dropout: 0.0
use_norm: ln
msg_transform: true
sum_transform: true
use_centroid: false
normalization_factor: 1
c: 0.01
proto_weight: 0.3 