model_type: ae
encoder: HGCN
enc_layers: 3
decoder: HGCN
dec_layers: 3
layer_type: HGCN
adj: ScoreNetworkA_poincare
x: ScoreNetworkX_poincare
use_centroid: true
act: LeakyReLU
adim: 32
aggregation_method: sum
c: 1
c_final: 4
c_hid: 8
c_init: 2
conv: GCN
depth: 5
dim: 10  #latent space dim
dropout: 0.0
edge_dim: 1
hidden_dim: 32
learnable_c: false
manifold: PoincareBall
msg_transform: true
nhid: 32
normalization_factor: 1
num_heads: 4
num_layers: 7
num_linears: 2
pred_edge: true
use_proto_loss: true
sum_transform: true
use_norm: ln






