# configs/model/classifier.yaml
model_type: classifier
ae_path: checkpoints/ENZYMES/ae_model_train/20250430_173628/best.pth
hidden_dim: 10 
num_layers: 2
dropout: 0.1
activation: LeakyReLU
use_batch_norm: false  # 禁用 BatchNorm
freeze_encoder: true