ae_path: checkpoints/ENZYMES/enzymes_ae/enzymes_ae_20250424_142945.pth
GCN_type: HGAT
act: LeakyReLU
adim: 32
adj: ScoreNetworkA_poincare
aggregation_method: sum
c: 0.01
c_final: 4
c_hid: 8
c_init: 2
conv: GCN
dec_layers: 3
depth: 5
dim: 10
dropout: 0.0
edge_dim: 1
enc_layers: 3
hidden_dim: 32
manifold: Lorentz
msg_transform: true
nhid: 32
normalization_factor: 1
num_heads: 4
num_layers: 7
num_linears: 2
sum_transform: true
use_centroid: false
use_norm: ln
x: ScoreNetworkX_poincare