model_type: HScoreNetworkA
max_feat_num: ${model.max_feat_num}  # 引用基础配置中的值
max_node_num: ${model.max_node_num}  # 引用基础配置中的值
nhid: 32
num_layers: 7
num_linears: 2
c_init: 2
c_hid: 8
c_final: 4
adim: 32
num_heads: 4
conv: GCN
manifold: Lorentz 
