# ENZYMES Poincaré VAE Training Configuration
# 针对ENZYMES数据集的VAE预训练配置

# 实验基本信息
exp_name: "enzymes_poincare_vae"
timestamp: "${now}"
run_name: "${exp_name}_${timestamp}"
debug: false
seed: 42
device: "auto"

# 数据集配置
data:
  name: "ENZYMES"
  batch_size: 256
  max_feat_num: 10
  max_node_num: 125
  test_class_num: 2  # 测试类别：[2,4]
  train_class_num: 4  # 训练类别：[1,3,5,6]
  test_split: 0.2
  degree_as_tag: true

# FSL任务配置 - 适配ENZYMES的类别数
fsl_task:
  N_way: 2  # 2个测试类别
  K_shot: 5
  R_query: 10
  meta_test_tasks: 500  # 与meta_test.num_test_tasks保持一致

# Wandb配置
wandb:
  project: "MHGDM_ENZYMES"
  entity: "huangyr_team"
  online: true
  no_wandb: false
  output_dir: "logs"  # wandb 输出目录

# ==================== VAE配置 ====================
vae:
  # 编码器配置
  encoder:
    type: "HyperbolicGraphEncoder"
    manifold_type: "PoincareBall"
    layer_type: "HGAT"
    curvature: 1.0
    learnable_curvature: false
    num_layers: 2  # 增加层数适应更复杂的分子结构
    hidden_feature_dim: 32  # 增加隐藏维度
    latent_feature_dim: 16  # 增加潜在维度
    input_feature_dim: 10
    dropout: 0.1
    aggregation_method: "sum"
    use_normalization: "ln"
  
  # 解码器配置
  decoder:
    type: "HyperbolicGraphDecoder"
    manifold_type: "PoincareBall"
    layer_type: "HGAT"
    curvature: 1.0
    learnable_curvature: false
    num_layers: 2
    hidden_feature_dim: 32
    latent_feature_dim: 16
    output_feature_dim: 10
    dropout: 0.1
    aggregation_method: "sum"
    use_normalization: "ln"
    use_centroid: false
  
  # 损失配置
  loss:
    pred_node_class: true
    pred_edge: true  # 启用边预测，对分子图重要
    use_kl_loss: true
    use_base_proto_loss: false
    use_sep_proto_loss: false
  
  # 训练配置
  train:
    num_epochs: 1500  # 增加训练轮数
    lr: 0.0005  # 稍微提高学习率
    lr_decay: 0.95 
    lr_schedule: true
    weight_decay: 0.0001
    grad_norm: 1.0
    
    # 损失权重
    rec_weight: 1.0
    kl_regularization: 0.0005  # 稍微增加KL正则化
    edge_weight: 0.05  # 增加边预测权重
    base_proto_weight: 0.0
    sep_proto_weight: 0.0
    
    # 测试间隔
    test_interval: 40

# ==================== Score Model配置 ====================
score:
  # X网络配置（节点特征）
  x:
    type: "ScoreNetworkX_poincare"
    manifold_type: "PoincareBall"
    depth: 4
    nhid: 64
    edge_dim: 1
    GCN_type: "HGCN"
  
  # Adj网络配置（邻接矩阵）
  adj:
    type: "ScoreNetworkA_poincare"
    manifold_type: "PoincareBall"
    nhid: 64
    num_layers: 4
    num_linears: 3
    c_init: 2
    c_hid: 8
    c_final: 4
    adim: 64
    num_heads: 8
    conv: "GCN"
  
  # SDE配置
  sde:
    x:
      type: "VP"
      beta_min: 0.1
      beta_max: 1.0
      num_scales: 1000
    adj:
      type: "VE"
      beta_min: 0.2
      beta_max: 1.0
      num_scales: 1000
      type: "VP"
      beta_min: 0.1
      beta_max: 1.0
      num_scales: 1000
    adj:
      type: "VE"
      beta_min: 0.2
      beta_max: 1.0
      num_scales: 1000
  
  # 训练配置
  train:
    num_epochs: 4000
    lr: 0.0001
    lr_decay: 0.999
    lr_schedule: true
    weight_decay: 0.0001
    grad_norm: 1.0
    ema: 0.999
    
    # 测试间隔
    test_interval: 400

# ==================== Meta-test配置 ====================
meta_test:
  # 数据增强配置
  data_augmentation:
    use_score_model: true
    k_augment: 3
  
  # 测试配置
  num_test_tasks: 500
  eval_support: true
  
  # 分类器配置
  classifier:
    epochs: 100
    lr: 0.001
    weight_decay: 0.0001
    dropout: 0.1
    bias: true
    patience: 10
  
  # 嵌入配置
  embedding:
    pooling_method: "mean_max"  # "mean", "max", "mean_max"
    normalize: false
  
  # 评估配置
  evaluation:
    confidence_interval: 0.95
    save_predictions: true
  
  # 日志配置
  logging:
    log_interval: 10

# ==================== 采样配置 ====================
sampler:
  corrector: "Langevin"
  n_steps: 1
  predictor: "Euler"
  scale_eps_A: 1.0
  scale_eps_x: 1.0
  snr_A: 0.25
  snr_x: 0.25
  proto_guide: false  # 移除 proto 条件控制
  eps: 0.0001
  noise_removal: true
  probability_flow: false
  use_ema: true

# ==================== 路径配置 ====================
paths:
  vae_checkpoint: null
  score_checkpoint: null
  save_dir: "./checkpoints/ENZYMES" 