# @package _global_
# configs/meta_test.yaml - Meta-learning test configuration

defaults: # 默认配置，会被后续的配置覆盖
  - base_config  # 引用 configs/base_config.yaml
  - /data/Letter_high  # 默认数据集配置
  - /fsl_task/5shot  # 默认少样本学习任务配置
  - _self_

# 实验配置
exp_name: "meta_test_${data.name}" # 实验名称
timestamp: ${now:%Y%m%d_%H%M%S} # 当前时间戳
run_name: ${exp_name}/${timestamp}  # 运行名称，自动组合实验名称和时间戳
debug: false # 是否开启调试模式

# 模型路径配置
model_paths:
  encoder_ckpt_path: "checkpoints/Letter_high/Letter_high_HGCN_encoder_train_20250524_200604/best.pth"  # 预训练编码器检查点路径
  score_ckpt_path: "checkpoints/Letter_high/Letter_high_score_network_proto_train_hgcn/20250525_000726/best.pth"    # 预训练分数模型检查点路径

# 数据增强配置
data_augmentation:
  use_score_model: true     # 是否使用分数模型进行数据增强
  k_augment: 2              # 每个样本生成的增强样本数量
  augment_mode: "prototype" # 增强模式: "prototype", "random", "interpolation"

# 采样配置 (仅当use_score_model=true时使用)
sampler:
  predictor: reverse_diffusion
  corrector: none
  snr_x: 0.15
  snr_A: 0.15
  scale_eps_x: 1.0
  scale_eps_A: 1.0
  n_steps: 1000
  probability_flow: False

sample:
  use_ema: true
  noise_removal: true
  sample_method: ddpm

# 元测试配置
meta_test:
  num_test_tasks: 600        # 测试任务数量
  eval_support: true         # 是否在支持集上评估
  eval_query: true           # 是否在查询集上评估
  
  # 分类头训练配置
  classifier:
    epochs: 100              # 分类头训练轮数
    lr: 0.01                 # 分类头学习率
    patience: 20             # 早停patience
    dropout: 0.0             # dropout率
    bias: true               # 是否使用bias
    optimizer: "Adam"        # 优化器类型
    weight_decay: 0.0        # 权重衰减
    
  # 嵌入处理配置
  embedding:
    pooling_method: "mean_max" # 池化方法: "mean", "max", "mean_max", "attention"
    normalize: false         # 是否标准化嵌入
    pca_dim: null           # PCA降维维度 (null表示不降维)

# 评估配置
evaluation:
  metrics: ["accuracy", "f1", "precision", "recall"]  # 评估指标
  confidence_interval: 0.95  # 置信区间
  save_predictions: false    # 是否保存预测结果
  save_embeddings: false     # 是否保存嵌入向量

# 日志配置
logging:
  log_interval: 10          # 日志记录间隔
  save_best_model: true     # 是否保存最佳模型
  log_confusion_matrix: true # 是否记录混淆矩阵

seed: 42 # 随机种子
device: auto # 运行设备 (例如 "cuda", "cpu", "auto" 表示自动选择)
device_count: 1 # 使用的设备数量
