# Reddit Poincaré VAE Training Configuration
# 针对Reddit大规模图数据集的VAE预训练配置

# 实验基本信息
exp_name: "reddit_poincare_vae"
timestamp: "${now}"
run_name: "${exp_name}_${timestamp}"
debug: false
seed: 42
device: "auto"

# 数据集配置 - 大规模图优化
data:
  name: "Reddit"
  batch_size: 1  # 大幅减小批次大小以适应大图
  max_feat_num: 525  # 524维特征 + 1
  max_node_num: 3782
  test_class_num: 4  # 根据实际数据：[2,4,8,10]
  train_class_num: 7  # 根据实际数据：[1,3,5,6,7,9,11]
  test_split: 0.2
  degree_as_tag: true
  # 大数据集优化选项
  enable_optimization: true
  lazy_tensor_conversion: true
  force_reload_data: false

# FSL任务配置 - 适配Reddit的类别数
fsl_task:
  N_way: 4  # Reddit测试集有4个类别：[2,4,8,10]
  K_shot: 3  # 减少shot数以加快训练
  R_query: 6  # 相应减少query数
  meta_test_tasks: 200  # 减少测试任务数

# Wandb配置
wandb:
  project: "MHGDM_Reddit"
  entity: "huangyr_team"
  online: true
  no_wandb: false

# ==================== VAE配置 ====================
vae:
  # 编码器配置 - 适应高维特征
  encoder:
    type: "HyperbolicGraphEncoder"
    manifold_type: "PoincareBall"
    layer_type: "HGAT"
    curvature: 0.5  # 减小曲率以适应大图
    learnable_curvature: true  # 启用可学习曲率
    num_layers: 3  # 减少层数避免过拟合
    hidden_feature_dim: 128  # 增加隐藏维度处理高维特征
    latent_feature_dim: 64   # 较大的潜在维度
    input_feature_dim: 525
    dropout: 0.2  # 增加dropout防止过拟合
    aggregation_method: "mean"  # 使用mean聚合避免梯度爆炸
    use_normalization: "bn"  # 使用batch norm稳定训练
  
  # 解码器配置
  decoder:
    type: "HyperbolicGraphDecoder"
    manifold_type: "PoincareBall"
    layer_type: "HGAT"
    curvature: 0.5
    learnable_curvature: true
    num_layers: 3
    hidden_feature_dim: 128
    latent_feature_dim: 64
    output_feature_dim: 525
    dropout: 0.2
    aggregation_method: "mean"
    use_normalization: "bn"
    use_centroid: true  # 启用质心使用
  
  # 损失配置
  loss:
    pred_node_class: true
    pred_edge: false  # 大图禁用边预测以节省计算
    pred_graph_class: true  # 启用图级分类
    use_kl_loss: true
    use_base_proto_loss: false
    use_sep_proto_loss: false
  
  # 训练配置 - 大图优化
  train:
    num_epochs: 800  # 减少训练轮数
    lr: 0.0005  # 降低学习率稳定训练
    lr_decay: 0.995  # 稍快的学习率衰减
    lr_schedule: true
    weight_decay: 0.001  # 增加权重衰减
    grad_norm: 0.5  # 更严格的梯度裁剪
    
    # 损失权重 - 大图调整
    rec_weight: 1.0
    kl_regularization: 0.00001  # 降低KL正则化
    edge_weight: 0.0  # 禁用边预测
    graph_classification_weight: 0.1  # 启用图级分类
    base_proto_weight: 0.0
    sep_proto_weight: 0.0
    
    # 测试间隔
    test_interval: 20

# ==================== Score Model配置 ====================
score:
  # X网络配置 - 高维特征优化
  x:
    type: "ScoreNetworkX_poincare"
    manifold_type: "PoincareBall"
    depth: 2  # 减少深度
    nhid: 64  # 减少隐藏维度
    edge_dim: 1
    GCN_type: "HGCN"
  
  # Adj网络配置 - 大图优化
  adj:
    type: "ScoreNetworkA_poincare"
    manifold_type: "PoincareBall"
    nhid: 32  # 大幅减少隐藏维度
    num_layers: 2  # 减少层数
    num_linears: 2
    c_init: 1
    c_hid: 4
    c_final: 2
    adim: 32
    num_heads: 4
    conv: "GCN"
  
  # SDE配置
  sde:
    x:
      type: "VP"
      beta_min: 0.05  # 减小noise范围
      beta_max: 0.5
      num_scales: 500  # 减少时间步数
    adj:
      type: "VE"
      beta_min: 0.1
      beta_max: 0.5
      num_scales: 500
  
  # 训练配置
  train:
    num_epochs: 2000  # 减少训练轮数
    lr: 0.00005  # 更小的学习率
    lr_decay: 0.999
    lr_schedule: true
    weight_decay: 0.001
    grad_norm: 0.5
    ema: 0.995  # 稍快的EMA
    
    # 测试间隔
    test_interval: 200

# ==================== Meta-test配置 ====================
meta_test:
  # 数据增强配置
  data_augmentation:
    use_score_model: false  # 大图禁用score model增强
    k_augment: 1
  
  # 测试配置
  num_test_tasks: 200  # 减少测试任务数
  eval_support: true
  
  # 分类器配置
  classifier:
    epochs: 50  # 减少分类器训练轮数
    lr: 0.001
    weight_decay: 0.001
    dropout: 0.3  # 增加dropout
    bias: true
    patience: 5  # 早停
  
  # 嵌入配置
  embedding:
    pooling_method: "mean"  # 只使用mean pooling
    normalize: true  # 启用归一化
  
  # 评估配置
  evaluation:
    confidence_interval: 0.95
    save_predictions: false  # 禁用预测保存节省空间
  
  # 日志配置
  logging:
    log_interval: 20

# ==================== 采样配置 ====================
sampler:
  corrector: "Langevin"
  n_steps: 1
  predictor: "Euler"
  scale_eps_A: 0.5  # 减小采样步长
  scale_eps_x: 0.5
  snr_A: 0.1
  snr_x: 0.1
  proto_guide: false  # 大图禁用prototype引导
  eps: 0.001
  noise_removal: true
  probability_flow: false
  use_ema: true

# ==================== 路径配置 ====================
paths:
  vae_checkpoint: null
  score_checkpoint: null
  save_dir: "./checkpoints/Reddit" 