# configs/ae.yaml
defaults:
  - data : ENZYMES
  - model : score
  - model/x: poincare_proto # 指定编码器
  - model/adj: poincare_proto # 指定解码器
  - train : train_score
  - _self_



# 实验配置
exp_name: "${model.model_type}_model_train"
timestamp: ${now:%Y%m%d_%H%M%S}
run_name: ${exp_name}_${timestamp}  # 自动组合exp_name和时间戳

debug: false

data:
  batch_size: 200

seed: 4
device: auto
device_count: 1

hydra:
  run:
    dir: .
  output_subdir: null
  job_logging:
    disable_existing_loggers: False
    formatters: null
    handlers: null
    root: null
    version: 1
  verbose: false

wandb:
  no_wandb: false
  online: true # Set to false for offline logging
  project: MHGDM
  wandb_usr: huangyr
  entity: huangyr_team



sde:
  adj:
    beta_max: 1.0
    beta_min: 0.2
    num_scales: 1000
    type: VE
  x:
    beta_max: 1.0
    beta_min: 0.1
    num_scales: 1000
    type: VP

train:
  ema: 0.999
  eps: 1.0e-05
  grad_norm: 1.0
  kl_regularization: 1.0e-05
  edge_weight: 1.0e-02
  proto_weight: 1.0e-02
  lr: 1e-2
  lr_decay: 0.999
  lr_schedule: true
  num_epochs: 5000
  print_interval: 10
  reduce_mean: true
  save_interval: 100
  weight_decay: 1e-04
  
