# @package _global_
# configs/train_hvae.yaml - HVAE Training Configuration

defaults: # 默认配置，会被后续的配置覆盖
  - base_config  # 引用 configs/base_config.yaml
  - /data/Letter_high  # 默认数据集配置
  - /fsl_task/5shot  # 默认少样本学习任务配置
  - /train/train_hvae  # HVAE训练配置
  - /encoder/hvae_encoder # HVAE encoder config
  - /decoder/base_hgcn_decoder # Decoder config
  - _self_

# 实验配置
exp_name: "${data.name}_HVAE_train" # 实验名称
timestamp: ${now:%Y%m%d_%H%M%S} # 当前时间戳
run_name: ${exp_name}/${timestamp}  # 运行名称，自动组合实验名称和时间戳
debug: false # 是否开启调试模式

# HVAE specific configuration
hvae:
  pred_node_class: true          # 是否预测节点分类
  use_kl_loss: true             # 是否使用KL散度损失
  use_base_proto_loss: true     # 是否使用基础原型损失
  use_sep_proto_loss: true      # 是否使用原型分离损失
  pred_edge: false              # 是否预测边
  pred_graph_class: true        # 是否预测图分类
  classifier_dropout: 0.0       # 分类器dropout
  classifier_bias: true         # 分类器偏置

# Training configuration
train:
  lr: 0.001
  weight_decay: 0.0001
  num_epochs: 500
  eval_interval: 50
  num_eval_tasks: 100
  
  # Loss weights for different HVAE components
  loss_weights:
    node_classification: 1.0     # 节点分类损失权重
    kl: 0.1                     # KL散度损失权重
    edge: 1.0                   # 边预测损失权重
    base_proto: 1.0             # 基础原型损失权重
    sep_proto: 0.1              # 原型分离损失权重
    graph_classification: 1.0    # 图分类损失权重

# 随机种子和设备配置
seed: 1
device: auto
device_count: 1
