# @package _global_
# configs/train_score_poincare_proto.yaml - Score Model Training Configuration

defaults: # 默认配置，会被后续的配置覆盖
  - base_config  # 引用 configs/base_config.yaml
  - /data/Letter_high  # 默认数据集配置
  - /fsl_task/5shot  # 默认少样本学习任务配置
  - /train/train_score  # 基础训练配
  - score_model_x: ScoreNetworkX_poincare # Load ScoreNetworkX config
  - score_model_a: ScoreNetworkA_poincare # Load ScoreNetworkA config
  - _self_

# 实验配置
exp_name: "${data.name}_score_network_proto_train_hgcn" # 实验名称
timestamp: ${now:%Y%m%d_%H%M%S} # 当前时间戳
run_name: ${exp_name}/${timestamp}  # 运行名称，自动组合实验名称和时间戳
debug: false # 是否开启调试模式

# 编码器路径配置
encoder_path: "checkpoints/Letter_high_HGCN_encoder_train/20250526_212414/best.pth"



# SDE配置
sde:
  adj:
    beta_max: 0.3
    beta_min: 0.1  # 改为与 x 相同
    num_scales: 1000
    type: VP       # 改为与 x 相同
  x:
    beta_max: 0.3
    beta_min: 0.1
    num_scales: 1000
    type: VP

# 随机种子和设备配置
seed: 1
device: auto
device_count: 1
