model_class: ScoreNetworkX_poincare_proto
manifold: PoincareBall
c: 1.0
max_feat_num: 64
nhid: 64
depth: 5
edge_dim: 1
GCN_type: HGCN
time_embedding_dim: 64
dropout: 0.0
activation: elu
use_batch_norm: false
use_centroid: false
normalization_factor: 1
num_heads: 4
conv: GCN
time_scale_layers: 2
use_time_conditioning: true
proto_weight: 0.1
