model_class: HGCN
input_feat_dim: 6
max_feat_num: 5
hidden_dim: 64
dim: 64
enc_layers: 3
layer_type: HGCN
dropout: 0.1
edge_dim: 1
normalization_factor: 1.0
aggregation_method: sum
msg_transform: linear
sum_transform: linear
use_norm: 'none'
manifold: PoincareBall
c: 1.0
learnable_c: false
use_centroid: false
input_manifold: null
