# GCN Encoder Configuration
model_class: GCN  # 编码器类型
input_feat_dim: ${data.max_feat_num} # 使用正确的Hydra语法引用数据集的特征维度
hidden_dim: 128
dim: 64
enc_layers: 2
layer_type: 'GCN'  # or 'GAT'
dropout: 0.1
edge_dim: 1 # Example value, adjust as needed
normalization_factor: 1.0 # Example value, adjust as needed
aggregation_method: 'sum' # Example value, adjust as needed (e.g., 'mean', 'max')
msg_transform: 'linear' # Example value, adjust as needed (e.g., 'mlp')
pred_edge: true # Example value, adjust as needed