exp_name: emzymes_score_model
ae_path: checkpoints/ENZYMES/enzymes_ae/enzymes_ae_20250422_162325.pth
data:
  batch_size: 128
  name: ENZYMES
  dir: datasets/
  init: degrees
  max_feat_num: 10
  max_node_num: 125
  test_split: 0.2
  train_class_num: 4
  test_class_num: 2
device: cuda:9
model:
  GCN_type: HGAT
  act: LeakyReLU
  adim: 32
  adj: ScoreNetworkA_poincare
  aggregation_method: sum
  c: 0.01
  c_final: 4
  c_hid: 8
  c_init: 2
  conv: GCN
  dec_layers: 3
  depth: 5
  dim: 10
  dropout: 0.0
  edge_dim: 1
  enc_layers: 3
  hidden_dim: 32
  manifold: Lorentz
  msg_transform: true
  nhid: 32
  normalization_factor: 1
  num_heads: 4
  num_layers: 7
  num_linears: 2
  sum_transform: true
  use_centroid: false
  use_norm: ln
  x: ScoreNetworkX_poincare

fsl:
  K_shot: 5
  N_way: 3
  P_num: 10
  query_size: 10

sde:
  adj:
    beta_max: 1.0
    beta_min: 0.2
    num_scales: 1000
    type: VE
  x:
    beta_max: 1.0
    beta_min: 0.1
    num_scales: 1000
    type: VP
seed: 1
train:
  ema: 0.999
  eps: 1.0e-05
  grad_norm: 1.0
  kl_regularization: 1.0e-05
  lr: 0.01
  lr_decay: 0.999
  lr_schedule: true
  num_epochs: 5000
  print_interval: 100
  reduce_mean: true
  save_interval: 500
  weight_decay: 0.0001
wandb:
  no_wandb: true
  online: true # Set to false for offline logging
  project: MHGDM
  wandb_usr: huangyr
  entity: huangyr_team


