ckpt: score_model
data:
  batch_size: 64
  data: ENZYMES
  dir: data/
  init: deg
  max_feat_num: 10
  max_node_num: 125
  test_split: 0.2
device: cuda:0
exp_name: '[score_model]_snr_x=0.25_scale_eps_x=1.0'
sample:
  eps: 0.0001
  noise_removal: true
  probability_flow: false
  seed: 1
  use_ema: true
sampler:
  corrector: Langevin
  n_steps: 1
  predictor: Euler
  scale_eps_A: '1.0'
  scale_eps_x: '1.0'
  snr_A: '0.25'
  snr_x: '0.25'
saved_name: score_model
seed: 1
wandb:
  no_wandb: true
  online: true
  project: enzymes_Sample
  wandb_usr: elma
