model_class: ScoreNetworkA_poincare_proto
max_feat_num: 64
max_node_num: 9
nhid: 64
num_layers: 5
num_linears: 3
c_init: 2
c_hid: 8
c_final: 4
adim: 64
num_heads: 4
conv: GCN
manifold: PoincareBall
proto_weight: 0.1
c: 1.0
