model_class: "ScoreNetworkA_poincare"
max_feat_num: 10
max_node_num: ${data.max_node_num}
nhid: 32
num_layers: 7
num_linears: 2
c_init: 2
c_hid: 8
c_final: 4
adim: 32
num_heads: 4
conv: "GCN"
manifold: "PoincareBall"
c: 1.0
